server: # REST and WS server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  plugins:
    # Modern YouTube plugin (replaces deprecated built-in YouTube)
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  
  server:
    password: "youshallnotpass"
    sources:
      # Disable deprecated YouTube source in favor of plugin
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false
      local: false
    
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    
    # High quality audio settings
    opusEncodingQuality: 10 # Maximum quality (0-10)
    resamplingQuality: HIGH # Best resampling (LOW/MEDIUM/HIGH)
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    
    timeouts:
      connectTimeoutMs: 5000
      connectionRequestTimeoutMs: 5000
      socketTimeoutMs: 10000

# Logging configuration
logging:
  file:
    path: ./logs/
  
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG # Enable YouTube plugin debug logging
  
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: false
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30

# Metrics (optional)
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
